In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Diabetes_data.csv to Diabetes_data.csv


In [ ]:
data=pd.read_csv('Diabetes_data.csv')
data.head()

Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0             0       1         1          1   40       1       0   
1             0       0         0          0   25       1       0   
2             0       1         1          1   28       0       0   
3             0       1         0          1   27       0       0   
4             0       1         1          1   24       0       0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                     0             0       0  ...              1   
1                     0             1       0  ...              0   
2                     0             0       1  ...              1   
3                     0             1       1  ...              1   
4                     0             1       1  ...              1   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  Education  \
0            0        5        18        15         1    0    9          4   
1            1        3         0         0         0    0    7          6   
2            1        5        30        30         1    0    9          4   
3            0        2         0         0         0    0   11          3   
4            0        2         3         0         0    0   11          5   

   Income  
0       3  
1       1  
2       8  
3       6  
4       4  

[5 rows x 22 columns]

In [ ]:
X=data[['BMI','MentHlth','PhysHlth','Age','Education','Income']]
X.head()

BMI  MentHlth  PhysHlth  Age  Education  Income
0   40        18        15    9          4       3
1   25         0         0    7          6       1
2   28        30        30    9          4       8
3   27         0         0   11          3       6
4   24         3         0   11          5       4

In [ ]:
print(data)

        Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0                  0       1         1          1   40       1       0   
1                  0       0         0          0   25       1       0   
2                  0       1         1          1   28       0       0   
3                  0       1         0          1   27       0       0   
4                  0       1         1          1   24       0       0   
...              ...     ...       ...        ...  ...     ...     ...   
253675             0       1         1          1   45       0       0   
253676             2       1         1          1   18       0       0   
253677             0       0         0          1   28       0       0   
253678             0       1         0          1   23       0       0   
253679             2       1         1          1   25       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                          0         

In [ ]:
data.isnull().sum()

Diabetes_012            0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [ ]:
data.shape

(253680, 22)

In [ ]:
for i in range(data.shape[1]):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [ ]:
for i in range(data.shape[1]):
  print(data.iloc[:,i].unique())
  print(data.iloc[:,i].value_counts())

[0 2 1]
Diabetes_012
0    213703
2     35346
1      4631
Name: count, dtype: int64
[1 0]
HighBP
0    144851
1    108829
Name: count, dtype: int64
[1 0]
HighChol
0    146089
1    107591
Name: count, dtype: int64
[1 0]
CholCheck
1    244210
0      9470
Name: count, dtype: int64
[40 25 28 27 24 30 34 26 33 21 23 22 38 32 37 31 29 20 35 45 39 19 47 18
 36 43 55 49 42 17 16 41 44 50 59 48 52 46 54 57 53 14 15 51 58 63 61 56
 74 62 64 66 73 85 60 67 65 70 82 79 92 68 72 88 96 13 81 71 75 12 77 69
 76 87 89 84 95 98 91 86 83 80 90 78]
BMI
27    24606
26    20562
24    19550
25    17146
28    16545
      ...  
85        1
91        1
86        1
90        1
78        1
Name: count, Length: 84, dtype: int64
[1 0]
Smoker
0    141257
1    112423
Name: count, dtype: int64
[0 1]
Stroke
0    243388
1     10292
Name: count, dtype: int64
[0 1]
HeartDiseaseorAttack
0    229787
1     23893
Name: count, dtype: int64
[0 1]
PhysActivity
1    191920
0     61760
Name: count, dtype: int64
[0 1]
Fruits
1    16

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          253680 non-null  int64
 1   HighBP                253680 non-null  int64
 2   HighChol              253680 non-null  int64
 3   CholCheck             253680 non-null  int64
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  int64
 6   Stroke                253680 non-null  int64
 7   HeartDiseaseorAttack  253680 non-null  int64
 8   PhysActivity          253680 non-null  int64
 9   Fruits                253680 non-null  int64
 10  Veggies               253680 non-null  int64
 11  HvyAlcoholConsump     253680 non-null  int64
 12  AnyHealthcare         253680 non-null  int64
 13  NoDocbcCost           253680 non-null  int64
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-n

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
data['Diabetes_012'].unique()

array([0, 2, 1])

In [ ]:
data['Diabetes_012']=data['Diabetes_012'].replace(2,1)

VIF

In [ ]:
X=data.drop(['Diabetes_012'],axis=1)
y = data['Diabetes_012']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, train_size=0.70)

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
def calc_vif(X):
   vif=pd.DataFrame()
   vif['variables']=X.columns
   vif["VIF"]=[variance_inflation_factor(X.values,i).round(1) for i in range(X.shape[1])]
   return(vif)
calc_vif(X_train)

variables   VIF
0                 HighBP   2.3
1               HighChol   2.0
2              CholCheck  23.3
3                    BMI  18.1
4                 Smoker   1.9
5                 Stroke   1.1
6   HeartDiseaseorAttack   1.3
7           PhysActivity   4.6
8                 Fruits   3.0
9                Veggies   5.8
10     HvyAlcoholConsump   1.1
11         AnyHealthcare  20.7
12           NoDocbcCost   1.2
13               GenHlth  10.7
14              MentHlth   1.5
15              PhysHlth   2.0
16              DiffWalk   1.8
17                   Sex   1.9
18                   Age   9.9
19             Education  29.5
20                Income  14.2

In [ ]:
calc_vif(X_train.drop(['Education'],axis=1))

variables   VIF
0                 HighBP   2.3
1               HighChol   2.0
2              CholCheck  22.3
3                    BMI  17.5
4                 Smoker   1.9
5                 Stroke   1.1
6   HeartDiseaseorAttack   1.3
7           PhysActivity   4.5
8                 Fruits   3.0
9                Veggies   5.7
10     HvyAlcoholConsump   1.1
11         AnyHealthcare  19.7
12           NoDocbcCost   1.2
13               GenHlth  10.8
14              MentHlth   1.5
15              PhysHlth   2.0
16              DiffWalk   1.8
17                   Sex   1.9
18                   Age   9.8
19                Income  11.4

In [ ]:
calc_vif(X_train.drop(['Education','CholCheck'],axis=1))

variables   VIF
0                 HighBP   2.3
1               HighChol   2.0
2                    BMI  16.1
3                 Smoker   1.9
4                 Stroke   1.1
5   HeartDiseaseorAttack   1.3
6           PhysActivity   4.5
7                 Fruits   3.0
8                Veggies   5.7
9      HvyAlcoholConsump   1.1
10         AnyHealthcare  18.0
11           NoDocbcCost   1.2
12               GenHlth  10.5
13              MentHlth   1.5
14              PhysHlth   2.0
15              DiffWalk   1.8
16                   Sex   1.9
17                   Age   9.5
18                Income  11.0

In [ ]:
calc_vif(X_train.drop(['Education','CholCheck','AnyHealthcare'],axis=1))

variables   VIF
0                 HighBP   2.3
1               HighChol   2.0
2                    BMI  14.7
3                 Smoker   1.9
4                 Stroke   1.1
5   HeartDiseaseorAttack   1.3
6           PhysActivity   4.4
7                 Fruits   3.0
8                Veggies   5.6
9      HvyAlcoholConsump   1.1
10           NoDocbcCost   1.2
11               GenHlth  10.2
12              MentHlth   1.5
13              PhysHlth   2.0
14              DiffWalk   1.8
15                   Sex   1.9
16                   Age   8.6
17                Income   9.5

In [ ]:
calc_vif(X_train.drop(['Education','CholCheck','AnyHealthcare','BMI'],axis=1))

variables  VIF
0                 HighBP  2.2
1               HighChol  2.0
2                 Smoker  1.9
3                 Stroke  1.1
4   HeartDiseaseorAttack  1.3
5           PhysActivity  4.3
6                 Fruits  3.0
7                Veggies  5.5
8      HvyAlcoholConsump  1.1
9            NoDocbcCost  1.2
10               GenHlth  8.3
11              MentHlth  1.5
12              PhysHlth  2.0
13              DiffWalk  1.8
14                   Sex  1.9
15                   Age  8.4
16                Income  8.0

In [ ]:
calc_vif(X_train.drop(['Education','CholCheck','AnyHealthcare','BMI','Age'],axis=1))

variables  VIF
0                 HighBP  2.1
1               HighChol  2.0
2                 Smoker  1.9
3                 Stroke  1.1
4   HeartDiseaseorAttack  1.3
5           PhysActivity  4.2
6                 Fruits  2.9
7                Veggies  5.5
8      HvyAlcoholConsump  1.1
9            NoDocbcCost  1.2
10               GenHlth  7.7
11              MentHlth  1.4
12              PhysHlth  2.0
13              DiffWalk  1.8
14                   Sex  1.9
15                Income  7.5

In [ ]:
calc_vif(X_train.drop(['Education','CholCheck','AnyHealthcare','BMI','Age','GenHlth'],axis=1))

variables  VIF
0                 HighBP  2.0
1               HighChol  1.9
2                 Smoker  1.8
3                 Stroke  1.1
4   HeartDiseaseorAttack  1.3
5           PhysActivity  4.2
6                 Fruits  2.9
7                Veggies  5.3
8      HvyAlcoholConsump  1.1
9            NoDocbcCost  1.1
10              MentHlth  1.4
11              PhysHlth  1.8
12              DiffWalk  1.7
13                   Sex  1.9
14                Income  6.8

In [ ]:
calc_vif(X_train.drop(['Education','CholCheck','AnyHealthcare','BMI','Age','GenHlth','Income'],axis=1))

variables  VIF
0                 HighBP  2.0
1               HighChol  1.9
2                 Smoker  1.8
3                 Stroke  1.1
4   HeartDiseaseorAttack  1.3
5           PhysActivity  3.5
6                 Fruits  2.8
7                Veggies  4.4
8      HvyAlcoholConsump  1.1
9            NoDocbcCost  1.1
10              MentHlth  1.4
11              PhysHlth  1.8
12              DiffWalk  1.7
13                   Sex  1.7

In [ ]:
calc_vif(X_train.drop(['Education','CholCheck','AnyHealthcare','BMI','Age','GenHlth','Income','Veggies'],axis=1))

variables  VIF
0                 HighBP  2.0
1               HighChol  1.9
2                 Smoker  1.8
3                 Stroke  1.1
4   HeartDiseaseorAttack  1.3
5           PhysActivity  2.8
6                 Fruits  2.3
7      HvyAlcoholConsump  1.1
8            NoDocbcCost  1.1
9               MentHlth  1.4
10              PhysHlth  1.8
11              DiffWalk  1.7
12                   Sex  1.7

fitting for original data

In [ ]:
constant1=sm.add_constant(X_train)
result=sm.Logit(y_train,constant1).fit()
print(result.summary())

Optimization terminated successfully.
         Current function value: 0.344551
         Iterations 8
                           Logit Regression Results                           
Dep. Variable:           Diabetes_012   No. Observations:               177576
Model:                          Logit   Df Residuals:                   177554
Method:                           MLE   Df Model:                           21
Date:                Wed, 14 Aug 2024   Pseudo R-squ.:                  0.2082
Time:                        12:48:55   Log-Likelihood:                -61184.
converged:                       True   LL-Null:                       -77269.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   -7.4622      0.103    -72.446      0.000      -7.664      -7.260

fitting model after removing vif greater than 3

In [ ]:
X_1=X.drop(['Education','CholCheck','AnyHealthcare','BMI','Age','GenHlth','Income','Veggies'],axis=1)
y_1=y
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.30, train_size=0.70)
constant=sm.add_constant(X_train_1)
log_model1=sm.Logit(y_train_1,constant)
result2=log_model1.fit()
print(result2.summary())

Optimization terminated successfully.
         Current function value: 0.373547
         Iterations 7
                           Logit Regression Results                           
Dep. Variable:           Diabetes_012   No. Observations:               177576
Model:                          Logit   Df Residuals:                   177562
Method:                           MLE   Df Model:                           13
Date:                Wed, 14 Aug 2024   Pseudo R-squ.:                  0.1424
Time:                        12:48:56   Log-Likelihood:                -66333.
converged:                       True   LL-Null:                       -77346.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   -2.7746      0.023   -122.526      0.000      -2.819      -2.730

fitting model for insignificant variable

In [ ]:
X_2=X.drop(['Smoker'], axis=1)
y_2=y
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, y_2, test_size=0.30, train_size=0.70)

In [ ]:
constant2=sm.add_constant(X_train_2)
log_model_IS=sm.Logit(y_train_2,constant2)
result_IS=log_model_IS.fit()
print(result_IS.summary())

Optimization terminated successfully.
         Current function value: 0.345584
         Iterations 8
                           Logit Regression Results                           
Dep. Variable:           Diabetes_012   No. Observations:               177576
Model:                          Logit   Df Residuals:                   177555
Method:                           MLE   Df Model:                           20
Date:                Wed, 14 Aug 2024   Pseudo R-squ.:                  0.2060
Time:                        12:48:58   Log-Likelihood:                -61367.
converged:                       True   LL-Null:                       -77292.
Covariance Type:            nonrobust   LLR p-value:                     0.000
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
const                   -7.4959      0.103    -72.525      0.000      -7.698      -7.293

logistic regression for original data

In [ ]:
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train, y_train)
predictions = logreg.predict(X_test)
print(predictions)
z=confusion_matrix(y_test, predictions)
z
print(classification_report(y_test,predictions))
accuracy_score(y_test,predictions)

[0 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91     64056
           1       0.54      0.16      0.25     12048

    accuracy                           0.85     76104
   macro avg       0.70      0.57      0.58     76104
weighted avg       0.81      0.85      0.81     76104



0.8453826342899191

after removing multi collinear variables

In [ ]:
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_1, y_train_1)
predictions1 = logreg.predict(X_test_1)
print(predictions1)
z=confusion_matrix(y_test_1, prediction1)
z
print(classification_report(y_test_1,predictions1))
accuracy_score(y_test_1,predictions1)

[0 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.98      0.91     64198
           1       0.52      0.11      0.19     11906

    accuracy                           0.84     76104
   macro avg       0.69      0.55      0.55     76104
weighted avg       0.80      0.84      0.80     76104



0.8446467991169978

after removing insignificant variables

In [ ]:
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_2, y_train_2)
predictions2 = logreg.predict(X_test_2)
print(predictions2)
z=confusion_matrix(y_test_2, predictions2)
z
print(classification_report(y_test_2,predictions2))
accuracy_score(y_test_2,predictions2)

[0 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.98      0.91     64029
           1       0.56      0.15      0.24     12075

    accuracy                           0.85     76104
   macro avg       0.71      0.56      0.57     76104
weighted avg       0.81      0.85      0.81     76104



0.846171029118049

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, train_size=0.60)
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train, y_train)
predictions3= logreg.predict(X_test)
print(predictions3)
z=confusion_matrix(y_test, predictions3)
z
print(classification_report(y_test,predictions3))
accuracy_score(y_test,predictions3)

[1 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91     85320
           1       0.55      0.18      0.27     16152

    accuracy                           0.85    101472
   macro avg       0.70      0.57      0.59    101472
weighted avg       0.81      0.85      0.81    101472



0.8457209870703248

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, train_size=0.60)
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_1, y_train_1)
predictions4 = logreg.predict(X_test_1)
print(predictions4)
z=confusion_matrix(y_test_1, predictions4)
z
print(classification_report(y_test_1,predictions4))
accuracy_score(y_test_1,predictions4)

[0 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.98      0.91     64213
           1       0.51      0.11      0.18     11891

    accuracy                           0.84     76104
   macro avg       0.68      0.55      0.55     76104
weighted avg       0.80      0.84      0.80     76104



0.844581099547987

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, train_size=0.60)
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_2, y_train_2)
predictions7 = logreg.predict(X_test_2)
print(predictions7)
z=confusion_matrix(y_test_2, predictions7)
z
print(classification_report(y_test_2,predictions7))
accuracy_score(y_test_2,predictions7)

[0 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91     64066
           1       0.53      0.19      0.28     12038

    accuracy                           0.85     76104
   macro avg       0.70      0.58      0.60     76104
weighted avg       0.81      0.85      0.81     76104



0.8452643750656995

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75)

In [ ]:
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train, y_train)
predictions5= logreg.predict(X_test)
print(predictions5)
z=confusion_matrix(y_test, predictions5)
z
print(classification_report(y_test,predictions5))
accuracy_score(y_test,predictions5)

[0 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.87      0.97      0.91     53549
           1       0.52      0.18      0.27      9871

    accuracy                           0.85     63420
   macro avg       0.69      0.58      0.59     63420
weighted avg       0.81      0.85      0.81     63420



0.8461684011352886

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75)
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_1, y_train_1)
predictions6 = logreg.predict(X_test_1)
print(predictions6)
z=confusion_matrix(y_test_1, predictions6)
z
print(classification_report(y_test_1,predictions6))
accuracy_score(y_test_1,predictions6)

[0 0 0 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.98      0.91     64213
           1       0.51      0.11      0.18     11891

    accuracy                           0.84     76104
   macro avg       0.68      0.55      0.55     76104
weighted avg       0.80      0.84      0.80     76104



0.844581099547987

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75)
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train_2, y_train_2)
predictions8 = logreg.predict(X_test_2)
print(predictions8)
z=confusion_matrix(y_test_2, predictions8)
z
print(classification_report(y_test_2,predictions8))
accuracy_score(y_test_2,predictions8)

[0 0 1 ... 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91     64066
           1       0.53      0.19      0.28     12038

    accuracy                           0.85     76104
   macro avg       0.70      0.58      0.60     76104
weighted avg       0.81      0.85      0.81     76104



0.8452643750656995

**KNN**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.30, train_size=0.70)

In [ ]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)
y_pred1=model.predict(X_test)
y_pred1

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
knn=pd.DataFrame({'Predicted':y_pred1,'Actual':y_test})
print(knn.head(10))
print(classification_report(y_test,y_pred1))
z=confusion_matrix(y_test,y_pred1)
print(z)
print(accuracy_score(y_test,y_pred1))

        Predicted  Actual
200462          0       0
82940           1       1
146087          1       0
168126          0       0
154056          0       0
99235           0       0
156994          0       0
142777          0       0
153476          0       0
197980          0       0
              precision    recall  f1-score   support

           0       0.87      0.94      0.90     64150
           1       0.42      0.23      0.29     11954

    accuracy                           0.83     76104
   macro avg       0.65      0.58      0.60     76104
weighted avg       0.80      0.83      0.81     76104

[[60481  3669]
 [ 9260  2694]]
0.8301140544518028


In [ ]:
model2=KNeighborsClassifier(n_neighbors=7)
model2.fit(X_train,y_train)
y_pred2=model2.predict(X_test)
y_pred2
knn=pd.DataFrame({'Predicted':y_pred2,'Actual':y_test})
print(knn.head(10))
print(classification_report(y_test,y_pred2))
z=confusion_matrix(y_test,y_pred2)
print(z)
print(accuracy_score(y_test,y_pred2))

        Predicted  Actual
200462          0       0
82940           0       1
146087          0       0
168126          0       0
154056          0       0
99235           0       0
156994          0       0
142777          0       0
153476          0       0
197980          0       0
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     64150
           1       0.45      0.20      0.28     11954

    accuracy                           0.84     76104
   macro avg       0.66      0.58      0.59     76104
weighted avg       0.80      0.84      0.81     76104

[[61156  2994]
 [ 9520  2434]]
0.8355671186797015


KNN for after removing vif greater than 3

In [ ]:
X_train_1,X_test_1,y_train_1,y_test_1=train_test_split(X_1, y_1, test_size=0.30, train_size=0.70)
model3=KNeighborsClassifier(n_neighbors=7)
model3.fit(X_train_1,y_train_1)
y_pred3=model3.predict(X_test_1)
y_pred3
knn=pd.DataFrame({'Predicted':y_pred3,'Actual':y_test_1})
print(knn.head(10))
print(classification_report(y_test_1,y_pred3))
z=confusion_matrix(y_test_1,y_pred3)
print(z)
print(accuracy_score(y_test_1,y_pred3))

        Predicted  Actual
2550            0       0
184419          0       0
238453          0       0
205440          0       0
37477           0       1
12432           0       0
247755          0       0
209483          0       0
98882           0       0
94666           0       0
              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.40      0.14      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61720  2523]
 [10181  1680]]
0.83307053505729


KNN for after removing insignificant variable

In [ ]:
X_train_2,X_test_2,y_train_2,y_test_2=train_test_split(X_2, y_2, test_size=0.30, train_size=0.70)
model4=KNeighborsClassifier(n_neighbors=7)
model4.fit(X_train_2,y_train_2)
y_pred4=model4.predict(X_test_2)
y_pred4
knn=pd.DataFrame({'Predicted':y_pred4,'Actual':y_test_2})
print(knn.head(10))
print(classification_report(y_test_2,y_pred4))
z=confusion_matrix(y_test_2,y_pred4)
print(z)
print(accuracy_score(y_test_2,y_pred4))

        Predicted  Actual
102507          0       0
240960          0       0
12966           0       0
10153           0       1
23538           0       0
38320           0       1
48072           0       1
195332          0       0
40124           0       0
194939          0       0
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     64099
           1       0.45      0.21      0.29     12005

    accuracy                           0.84     76104
   macro avg       0.66      0.58      0.60     76104
weighted avg       0.80      0.84      0.81     76104

[[61030  3069]
 [ 9475  2530]]
0.8351729212656365


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.40, train_size=0.60)
model5=KNeighborsClassifier(n_neighbors=7)
model5.fit(X_train,y_train)
y_pred5=model5.predict(X_test)
y_pred5
knn=pd.DataFrame({'Predicted':y_pred5,'Actual':y_test})
print(knn.head(10))
print(classification_report(y_test,y_pred5))
z=confusion_matrix(y_test,y_pred5)
print(z)
print(accuracy_score(y_test,y_pred5))

        Predicted  Actual
18688           0       0
184438          0       0
239921          0       0
53491           0       0
111145          0       0
210862          0       0
70477           0       0
134928          0       0
235169          0       0
136747          0       0
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     85482
           1       0.45      0.20      0.28     15990

    accuracy                           0.84    101472
   macro avg       0.66      0.58      0.59    101472
weighted avg       0.80      0.84      0.81    101472

[[81546  3936]
 [12722  3268]]
0.8358364869126459


In [ ]:
model6=KNeighborsClassifier(n_neighbors=7)
model6.fit(X_train_1,y_train_1)
y_pred6=model6.predict(X_test_1)
y_pred6
knn=pd.DataFrame({'Predicted':y_pred6,'Actual':y_test_1})
print(knn.head(10))
print(classification_report(y_test_1,y_pred6))
z=confusion_matrix(y_test_1,y_pred6)
print(z)
print(accuracy_score(y_test_1,y_pred6))

        Predicted  Actual
2550            0       0
184419          0       0
238453          0       0
205440          0       0
37477           0       1
12432           0       0
247755          0       0
209483          0       0
98882           0       0
94666           0       0
              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.40      0.14      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61720  2523]
 [10181  1680]]
0.83307053505729


In [ ]:
model7=KNeighborsClassifier(n_neighbors=7)
model7.fit(X_train_2,y_train_2)
y_pred7=model7.predict(X_test_2)
y_pred7
knn=pd.DataFrame({'Predicted':y_pred7,'Actual':y_test_2})
print(knn.head(10))
print(classification_report(y_test_2,y_pred7))
z=confusion_matrix(y_test_2,y_pred7)
print(z)
print(accuracy_score(y_test_2,y_pred7))

        Predicted  Actual
102507          0       0
240960          0       0
12966           0       0
10153           0       1
23538           0       0
38320           0       1
48072           0       1
195332          0       0
40124           0       0
194939          0       0
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     64099
           1       0.45      0.21      0.29     12005

    accuracy                           0.84     76104
   macro avg       0.66      0.58      0.60     76104
weighted avg       0.80      0.84      0.81     76104

[[61030  3069]
 [ 9475  2530]]
0.8351729212656365


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.25, train_size=0.75)
model8=KNeighborsClassifier(n_neighbors=7)
model8.fit(X_train,y_train)
y_pred8=model8.predict(X_test)
y_pred8
knn=pd.DataFrame({'Predicted':y_pred8,'Actual':y_test})
print(knn.head(10))
print(classification_report(y_test,y_pred8))
z=confusion_matrix(y_test,y_pred8)
print(z)
print(accuracy_score(y_test,y_pred8))

        Predicted  Actual
116918          0       0
43935           0       0
10310           0       0
38873           0       0
81584           0       1
186533          0       0
87693           0       0
61896           0       0
227890          0       0
98916           0       0
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     53530
           1       0.45      0.21      0.28      9890

    accuracy                           0.84     63420
   macro avg       0.66      0.58      0.60     63420
weighted avg       0.80      0.84      0.81     63420

[[51013  2517]
 [ 7843  2047]]
0.8366445916114791


In [ ]:
model9=KNeighborsClassifier(n_neighbors=7)
model9.fit(X_train_1,y_train_1)
y_pred9=model9.predict(X_test_1)
y_pred9
knn=pd.DataFrame({'Predicted':y_pred9,'Actual':y_test_1})
print(knn.head(10))
print(classification_report(y_test_1,y_pred9))
z=confusion_matrix(y_test_1,y_pred9)
print(z)
print(accuracy_score(y_test_1,y_pred9))

        Predicted  Actual
2550            0       0
184419          0       0
238453          0       0
205440          0       0
37477           0       1
12432           0       0
247755          0       0
209483          0       0
98882           0       0
94666           0       0
              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.40      0.14      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61720  2523]
 [10181  1680]]
0.83307053505729


In [ ]:
model10=KNeighborsClassifier(n_neighbors=7)
model10.fit(X_train_2,y_train_2)
y_pred10=model10.predict(X_test_2)
y_pred10
knn=pd.DataFrame({'Predicted':y_pred10,'Actual':y_test_2})
print(knn.head(10))
print(classification_report(y_test_2,y_pred10))
z=confusion_matrix(y_test_2,y_pred10)
print(z)
print(accuracy_score(y_test_2,y_pred10))

        Predicted  Actual
102507          0       0
240960          0       0
12966           0       0
10153           0       1
23538           0       0
38320           0       1
48072           0       1
195332          0       0
40124           0       0
194939          0       0
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     64099
           1       0.45      0.21      0.29     12005

    accuracy                           0.84     76104
   macro avg       0.66      0.58      0.60     76104
weighted avg       0.80      0.84      0.81     76104

[[61030  3069]
 [ 9475  2530]]
0.8351729212656365


In [ ]:
data = {'0.70-0.30': [0.8345, 0.8275,0.8354 ],'0.60-0.40': [0.8346,0.8275 , 0.8354],'0.75-0.25': [0.8335,0.8275 ,0.8354]}
data = pd.DataFrame(data)
print(data)

   0.70-0.30  0.60-0.40  0.75-0.25
0     0.8345     0.8346     0.8335
1     0.8275     0.8275     0.8275
2     0.8354     0.8354     0.8354


Decision Tree Classification

for original data

In [ ]:
clf1=DecisionTreeClassifier()
clf1=clf1.fit(X_train,y_train)
y_pred1=clf1.predict(X_test)
DTC=pd.DataFrame({"predicted":y_pred1,"actual":y_test})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred1))

        predicted  actual
116918          0       0
43935           0       0
10310           0       0
38873           0       0
81584           0       1
...           ...     ...
6015            0       0
46304           0       0
113079          0       0
168419          1       1
156926          0       0

[63420 rows x 2 columns]
Accuracy: 0.7763323872595396


In [ ]:
clf=DecisionTreeClassifier(criterion="entropy",max_depth=3)
clf=clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
DTC=pd.DataFrame({"predicted":y_pred,"actual":y_test})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

        predicted  actual
116918          0       0
43935           0       0
10310           0       0
38873           0       0
81584           0       1
...           ...     ...
6015            0       0
46304           0       0
113079          0       0
168419          0       1
156926          0       0

[63420 rows x 2 columns]
Accuracy: 0.8440555029959004


In [ ]:
clf=DecisionTreeClassifier(criterion="gini",max_depth=6)
clf=clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
DTC=pd.DataFrame({"predicted":y_pred,"actual":y_test})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

        predicted  actual
116918          0       0
43935           0       0
10310           0       0
38873           0       0
81584           0       1
...           ...     ...
6015            0       0
46304           0       0
113079          0       0
168419          0       1
156926          0       0

[63420 rows x 2 columns]
Accuracy: 0.8507568590350048


decisiontreeclassification after removing vif greater than 3

In [ ]:
clf2=DecisionTreeClassifier()
clf2=clf2.fit(X_train_1,y_train_1)
y_pred2=clf2.predict(X_test_1)
print(y_pred2)
DTC=pd.DataFrame({"predicted":y_pred2,"actual":y_test_1})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test_1,y_pred2))

[0 0 0 ... 0 0 0]
        predicted  actual
2550            0       0
184419          0       0
238453          0       0
205440          0       0
37477           0       1
...           ...     ...
242171          0       0
67839           0       0
40158           0       0
112337          0       0
147896          0       0

[76104 rows x 2 columns]
Accuracy: 0.8289577420372123


decisiontreeclassification after removing insignificant variable

In [ ]:
clf3=DecisionTreeClassifier()
clf3=clf3.fit(X_train_2,y_train_2)
y_pred3=clf3.predict(X_test_2)
print(y_pred3)
DTC=pd.DataFrame({"predicted":y_pred3,"actual":y_test_2})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test_2,y_pred3))

[0 0 0 ... 0 0 0]
        predicted  actual
102507          0       0
240960          0       0
12966           0       0
10153           0       1
23538           0       0
...           ...     ...
116289          0       0
84643           0       0
108323          0       0
195529          0       1
226478          0       0

[76104 rows x 2 columns]
Accuracy: 0.7806028592452433


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.40, train_size=0.60)
clf4=DecisionTreeClassifier()
clf4=clf4.fit(X_train,y_train)
y_pred4=clf4.predict(X_test)
DTC=pd.DataFrame({"predicted":y_pred4,"actual":y_test})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred4))

        predicted  actual
164354          1       0
17203           0       1
110474          1       0
120398          1       0
139240          0       0
...           ...     ...
17324           0       0
114455          0       0
101990          0       0
82198           0       0
165768          0       1

[101472 rows x 2 columns]
Accuracy: 0.7786975717439294


In [ ]:
clf5=DecisionTreeClassifier()
clf5=clf5.fit(X_train_1,y_train_1)
y_pred5=clf5.predict(X_test_1)
print(y_pred5)
DTC=pd.DataFrame({"predicted":y_pred5,"actual":y_test_1})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test_1,y_pred5))

[0 0 0 ... 0 0 0]
        predicted  actual
2550            0       0
184419          0       0
238453          0       0
205440          0       0
37477           0       1
...           ...     ...
242171          0       0
67839           0       0
40158           0       0
112337          0       0
147896          0       0

[76104 rows x 2 columns]
Accuracy: 0.8292074003994534


In [ ]:
clf6=DecisionTreeClassifier()
clf6=clf6.fit(X_train_2,y_train_2)
y_pred6=clf6.predict(X_test_2)
print(y_pred6)
DTC=pd.DataFrame({"predicted":y_pred6,"actual":y_test_2})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test_2,y_pred6))

[0 0 0 ... 0 0 0]
        predicted  actual
102507          0       0
240960          0       0
12966           0       0
10153           0       1
23538           0       0
...           ...     ...
116289          0       0
84643           0       0
108323          0       0
195529          0       1
226478          0       0

[76104 rows x 2 columns]
Accuracy: 0.7822847682119205


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.25, train_size=0.75)
clf7=DecisionTreeClassifier()
clf7=clf7.fit(X_train,y_train)
y_pred7=clf7.predict(X_test)
DTC=pd.DataFrame({"predicted":y_pred7,"actual":y_test})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test,y_pred7))

        predicted  actual
111762          1       1
7569            0       0
84599           0       0
116986          0       0
77953           1       0
...           ...     ...
172637          0       1
115150          0       0
241770          0       0
24581           0       0
142185          1       0

[63420 rows x 2 columns]
Accuracy: 0.7789498580889309


In [ ]:
clf8=DecisionTreeClassifier()
clf8=clf8.fit(X_train_1,y_train_1)
y_pred8=clf8.predict(X_test_1)
print(y_pred8)
DTC=pd.DataFrame({"predicted":y_pred8,"actual":y_test_1})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test_1,y_pred8))

[0 0 0 ... 0 0 0]
        predicted  actual
2550            0       0
184419          0       0
238453          0       0
205440          0       0
37477           0       1
...           ...     ...
242171          0       0
67839           0       0
40158           0       0
112337          0       0
147896          0       0

[76104 rows x 2 columns]
Accuracy: 0.8289708819510144


In [ ]:
clf9=DecisionTreeClassifier()
clf9=clf9.fit(X_train_2,y_train_2)
y_pred9=clf9.predict(X_test_2)
print(y_pred9)
DTC=pd.DataFrame({"predicted":y_pred9,"actual":y_test_2})
print(DTC)
print("Accuracy:",metrics.accuracy_score(y_test_2,y_pred9))

[0 0 0 ... 0 0 0]
        predicted  actual
102507          0       0
240960          0       0
12966           0       0
10153           0       1
23538           0       0
...           ...     ...
116289          0       0
84643           0       0
108323          0       0
195529          0       1
226478          0       0

[76104 rows x 2 columns]
Accuracy: 0.7806948386418585


In [ ]:
data = {'0.70-0.30': [0.7756, 0.8273,0.7798 ],'0.60-0.40': [0.7778,0.8271 , 0.7796],'0.75-0.25': [ 0.7805,0.8270 ,0.7804]}
data = pd.DataFrame(data)
print(data)

   0.70-0.30  0.60-0.40  0.75-0.25
0     0.7756     0.7778     0.7805
1     0.8273     0.8271     0.8270
2     0.7798     0.7796     0.7804


**random** **forest**

for original data

In [ ]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     53371
           1       0.51      0.21      0.30     10049

    accuracy                           0.84     63420
   macro avg       0.69      0.59      0.61     63420
weighted avg       0.81      0.84      0.81     63420

[[51332  2039]
 [ 7918  2131]]
0.8429990539262062


after removing vif greater than 3

In [ ]:
rf1=RandomForestClassifier()
rf1.fit(X_train_1,y_train_1)
y_pred1=rf1.predict(X_test_1)
print(classification_report(y_test_1,y_pred1))
print(confusion_matrix(y_test_1,y_pred1))
print(accuracy_score(y_test_1,y_pred1))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.39      0.14      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61621  2622]
 [10153  1708]]
0.8321376011773363


after removing insignificant variable

In [ ]:
rf2=RandomForestClassifier()
rf2.fit(X_train_2,y_train_2)
y_pred2=rf2.predict(X_test_2)
print(classification_report(y_test_2,y_pred2))
print(confusion_matrix(y_test_2,y_pred2))
print(accuracy_score(y_test_2,y_pred2))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     64099
           1       0.48      0.22      0.30     12005

    accuracy                           0.84     76104
   macro avg       0.67      0.59      0.60     76104
weighted avg       0.81      0.84      0.81     76104

[[61306  2793]
 [ 9408  2597]]
0.8396799116997793


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.40, train_size=0.60)
rf3=RandomForestClassifier()
rf3.fit(X_train,y_train)
y_pred3=rf.predict(X_test)
print(classification_report(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97     85531
           1       0.94      0.78      0.85     15941

    accuracy                           0.96    101472
   macro avg       0.95      0.88      0.91    101472
weighted avg       0.96      0.96      0.95    101472

[[84675   856]
 [ 3552 12389]]
0.956559444970041


In [ ]:
rf4=RandomForestClassifier()
rf4.fit(X_train_1,y_train_1)
y_pred4=rf4.predict(X_test_1)
print(classification_report(y_test_1,y_pred4))
print(confusion_matrix(y_test_1,y_pred4))
print(accuracy_score(y_test_1,y_pred4))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.40      0.15      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61592  2651]
 [10121  1740]]
0.8321770209187428


In [ ]:
rf5=RandomForestClassifier()
rf5.fit(X_train_2,y_train_2)
y_pred5=rf5.predict(X_test_2)
print(classification_report(y_test_2,y_pred5))
print(confusion_matrix(y_test_2,y_pred5))
print(accuracy_score(y_test_2,y_pred5))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     64099
           1       0.48      0.22      0.30     12005

    accuracy                           0.84     76104
   macro avg       0.67      0.59      0.60     76104
weighted avg       0.81      0.84      0.81     76104

[[61319  2780]
 [ 9420  2585]]
0.8396930516135814


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.25, train_size=0.75)
rf6=RandomForestClassifier()
rf6.fit(X_train,y_train)
y_pred6=rf.predict(X_test)
print(classification_report(y_test,y_pred6))
print(confusion_matrix(y_test,y_pred6))
print(accuracy_score(y_test,y_pred6))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97     53567
           1       0.93      0.77      0.85      9853

    accuracy                           0.96     63420
   macro avg       0.95      0.88      0.91     63420
weighted avg       0.96      0.96      0.95     63420

[[53001   566]
 [ 2228  7625]]
0.9559444970040997


In [ ]:
rf7=RandomForestClassifier()
rf7.fit(X_train_1,y_train_1)
y_pred7=rf7.predict(X_test_1)
print(classification_report(y_test_1,y_pred7))
print(confusion_matrix(y_test_1,y_pred7))
print(accuracy_score(y_test_1,y_pred7))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.40      0.15      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61609  2634]
 [10124  1737]]
0.8323609797119731


In [ ]:
rf8=RandomForestClassifier()
rf8.fit(X_train_2,y_train_2)
y_pred8=rf8.predict(X_test_2)
print(classification_report(y_test_2,y_pred8))
print(confusion_matrix(y_test_2,y_pred8))
print(accuracy_score(y_test_2,y_pred8))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     64099
           1       0.48      0.22      0.30     12005

    accuracy                           0.84     76104
   macro avg       0.67      0.59      0.61     76104
weighted avg       0.81      0.84      0.81     76104

[[61264  2835]
 [ 9375  2630]]
0.8395616524755598


In [ ]:
data = {'0.70-0.30': [0.8419, 0.8315,0.8387 ],'0.60-0.40': [0.9567,0.8317 , 0.8393],'0.75-0.25': [ 0.9557,0.8316 ,0.8316]}
data = pd.DataFrame(data)
print(data)

   0.70-0.30  0.60-0.40  0.75-0.25
0     0.8419     0.9567     0.9557
1     0.8315     0.8317     0.8316
2     0.8387     0.8393     0.8316


**Bagging**

for original data

In [ ]:
base_model=DecisionTreeClassifier(max_features="sqrt")
bagging_model=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model.fit(X_train,y_train)
y_pred=bagging_model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91     53567
           1       0.45      0.20      0.28      9853

    accuracy                           0.84     63420
   macro avg       0.66      0.58      0.59     63420
weighted avg       0.80      0.84      0.81     63420

[[51120  2447]
 [ 7843  2010]]
0.8377483443708609


after removing vif greater than 3

In [ ]:
base_model1=DecisionTreeClassifier(max_features="sqrt")
bagging_model1=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model1.fit(X_train_1,y_train_1)
predictions1=bagging_model1.predict(X_test_1)
print(classification_report(y_test_1,y_pred1))
print(confusion_matrix(y_test_1,y_pred1))
print(accuracy_score(y_test_1,y_pred1))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.39      0.14      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61621  2622]
 [10153  1708]]
0.8321376011773363


after removing insignificant variable

In [ ]:
base_model2=DecisionTreeClassifier(max_features="sqrt")
bagging_model2=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model2.fit(X_train_2,y_train_2)
predictions2=bagging_model2.predict(X_test_2)
print(classification_report(y_test_2,y_pred2))
print(confusion_matrix(y_test_2,y_pred2))
print(accuracy_score(y_test_2,y_pred2))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     64099
           1       0.48      0.22      0.30     12005

    accuracy                           0.84     76104
   macro avg       0.67      0.59      0.60     76104
weighted avg       0.81      0.84      0.81     76104

[[61306  2793]
 [ 9408  2597]]
0.8396799116997793


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.40, train_size=0.60)
base_model3=DecisionTreeClassifier(max_features="sqrt")
bagging_model3=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model3.fit(X_train,y_train)
predictions3=bagging_model.predict(X_test)
print(classification_report(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.84      0.87      0.86     85339
           1       0.16      0.13      0.15     16133

    accuracy                           0.75    101472
   macro avg       0.50      0.50      0.50    101472
weighted avg       0.73      0.75      0.74    101472

[[74235 11104]
 [13992  2141]]
0.7526805424156418


In [ ]:
base_model4=DecisionTreeClassifier(max_features="sqrt")
bagging_model4=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model4.fit(X_train_1,y_train_1)
predictions4=bagging_model4.predict(X_test_1)
print(classification_report(y_test_1,y_pred4))
print(confusion_matrix(y_test_1,y_pred4))
print(accuracy_score(y_test_1,y_pred4))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.40      0.15      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61592  2651]
 [10121  1740]]
0.8321770209187428


In [ ]:
base_model5=DecisionTreeClassifier(max_features="sqrt")
bagging_model5=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model5.fit(X_train_2,y_train_2)
predictions5=bagging_model5.predict(X_test_2)
print(classification_report(y_test_2,y_pred5))
print(confusion_matrix(y_test_2,y_pred5))
print(accuracy_score(y_test_2,y_pred5))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     64099
           1       0.48      0.22      0.30     12005

    accuracy                           0.84     76104
   macro avg       0.67      0.59      0.60     76104
weighted avg       0.81      0.84      0.81     76104

[[61319  2780]
 [ 9420  2585]]
0.8396930516135814


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.25, train_size=0.75)
base_model6=DecisionTreeClassifier(max_features="sqrt")
bagging_model6=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model6.fit(X_train,y_train)
predictions6=bagging_model6.predict(X_test)
print(classification_report(y_test,y_pred6))
print(confusion_matrix(y_test,y_pred6))
print(accuracy_score(y_test,y_pred6))

              precision    recall  f1-score   support

           0       0.84      0.87      0.86     53355
           1       0.16      0.13      0.15     10065

    accuracy                           0.75     63420
   macro avg       0.50      0.50      0.50     63420
weighted avg       0.73      0.75      0.74     63420

[[46507  6848]
 [ 8722  1343]]
0.7544938505203406


In [ ]:
base_model7=DecisionTreeClassifier(max_features="sqrt")
bagging_model7=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model7.fit(X_train_1,y_train_1)
predictions7=bagging_model7.predict(X_test_1)
print(classification_report(y_test_1,y_pred7))
print(confusion_matrix(y_test_1,y_pred7))
print(accuracy_score(y_test_1,y_pred7))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     64243
           1       0.40      0.15      0.21     11861

    accuracy                           0.83     76104
   macro avg       0.63      0.55      0.56     76104
weighted avg       0.79      0.83      0.80     76104

[[61609  2634]
 [10124  1737]]
0.8323609797119731


In [ ]:
base_model8=DecisionTreeClassifier(max_features="sqrt")
bagging_model8=BaggingClassifier(base_model, n_estimators=10,random_state=1)
bagging_model8.fit(X_train_2,y_train_2)
predictions8=bagging_model8.predict(X_test_2)
print(classification_report(y_test_2,y_pred8))
print(confusion_matrix(y_test_2,y_pred8))
print(accuracy_score(y_test_2,y_pred8))

              precision    recall  f1-score   support

           0       0.87      0.96      0.91     64099
           1       0.48      0.22      0.30     12005

    accuracy                           0.84     76104
   macro avg       0.67      0.59      0.61     76104
weighted avg       0.81      0.84      0.81     76104

[[61264  2835]
 [ 9375  2630]]
0.8395616524755598


In [ ]:
data = {'0.70-0.30': [0.8373, 0.8315,0.8387 ],'0.60-0.40': [0.7527,0.8317 , 0.8393],'0.75-0.25': [ 0.7528,0.8316 ,0.8389]}
data = pd.DataFrame(data)
print(data)

   0.70-0.30  0.60-0.40  0.75-0.25
0     0.8373     0.7527     0.7528
1     0.8315     0.8317     0.8316
2     0.8387     0.8393     0.8389


Boosting

for original data

In [ ]:
gdc=GradientBoostingClassifier()
gdc.fit(X_train,y_train)
y_pred=gdc.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92     53355
           1       0.57      0.21      0.30     10065

    accuracy                           0.85     63420
   macro avg       0.72      0.59      0.61     63420
weighted avg       0.82      0.85      0.82     63420

[[51816  1539]
 [ 7991  2074]]
0.8497319457584358


after removing vif greater than 3

In [ ]:
gdc1=GradientBoostingClassifier()
gdc1.fit(X_train_1,y_train_1)
y_pred1=gdc1.predict(X_test_1)
print(classification_report(y_test_1,y_pred1))
print(confusion_matrix(y_test_1,y_pred1))
print(accuracy_score(y_test_1,y_pred1))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92     64243
           1       0.53      0.10      0.16     11861

    accuracy                           0.85     76104
   macro avg       0.69      0.54      0.54     76104
weighted avg       0.80      0.85      0.80     76104

[[63211  1032]
 [10704  1157]]
0.8457899716177862


after removing insignificant variable

In [ ]:
gdc2=GradientBoostingClassifier()
gdc2.fit(X_train_2,y_train_2)
y_pred2=gdc2.predict(X_test_2)
print(classification_report(y_test_2,y_pred2))
print(confusion_matrix(y_test_2,y_pred2))
print(accuracy_score(y_test_2,y_pred2))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92     64099
           1       0.57      0.21      0.31     12005

    accuracy                           0.85     76104
   macro avg       0.72      0.59      0.61     76104
weighted avg       0.82      0.85      0.82     76104

[[62234  1865]
 [ 9491  2514]]
0.850783138862609


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.40, train_size=0.60)
gdc3=GradientBoostingClassifier()
gdc3.fit(X_train,y_train)
y_pred3=gdc3.predict(X_test)
print(classification_report(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92     85505
           1       0.58      0.21      0.30     15967

    accuracy                           0.85    101472
   macro avg       0.72      0.59      0.61    101472
weighted avg       0.82      0.85      0.82    101472

[[83067  2438]
 [12656  3311]]
0.8512496058025859


In [ ]:
gdc4=GradientBoostingClassifier()
gdc4.fit(X_train_1,y_train_1)
y_pred4=gdc4.predict(X_test_1)
print(classification_report(y_test_1,y_pred4))
print(confusion_matrix(y_test_1,y_pred4))
print(accuracy_score(y_test_1,y_pred4))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92     64243
           1       0.53      0.10      0.16     11861

    accuracy                           0.85     76104
   macro avg       0.69      0.54      0.54     76104
weighted avg       0.80      0.85      0.80     76104

[[63211  1032]
 [10704  1157]]
0.8457899716177862


In [ ]:
gdc5=GradientBoostingClassifier()
gdc5.fit(X_train_2,y_train_2)
y_pred5=gdc5.predict(X_test_2)
print(classification_report(y_test_2,y_pred5))
print(confusion_matrix(y_test_2,y_pred5))
print(accuracy_score(y_test_2,y_pred5))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92     64099
           1       0.57      0.21      0.31     12005

    accuracy                           0.85     76104
   macro avg       0.72      0.59      0.61     76104
weighted avg       0.82      0.85      0.82     76104

[[62234  1865]
 [ 9491  2514]]
0.850783138862609


In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.25, train_size=0.75)
gdc6=GradientBoostingClassifier()
gdc6.fit(X_train,y_train)
y_pred6=gdc6.predict(X_test)
print(classification_report(y_test,y_pred6))
print(confusion_matrix(y_test,y_pred6))
print(accuracy_score(y_test,y_pred6))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92     53417
           1       0.59      0.21      0.31     10003

    accuracy                           0.85     63420
   macro avg       0.73      0.59      0.61     63420
weighted avg       0.82      0.85      0.82     63420

[[51982  1435]
 [ 7939  2064]]
0.8521917376222012


In [ ]:
gdc7=GradientBoostingClassifier()
gdc7.fit(X_train_1,y_train_1)
y_pred7=gdc7.predict(X_test_1)
print(classification_report(y_test_1,y_pred7))
print(confusion_matrix(y_test_1,y_pred7))
print(accuracy_score(y_test_1,y_pred7))

              precision    recall  f1-score   support

           0       0.86      0.98      0.92     64243
           1       0.53      0.10      0.16     11861

    accuracy                           0.85     76104
   macro avg       0.69      0.54      0.54     76104
weighted avg       0.80      0.85      0.80     76104

[[63211  1032]
 [10704  1157]]
0.8457899716177862


In [ ]:
gdc8=GradientBoostingClassifier()
gdc8.fit(X_train_2,y_train_2)
y_pred8=gdc8.predict(X_test_2)
print(classification_report(y_test_2,y_pred8))
print(confusion_matrix(y_test_2,y_pred8))
print(accuracy_score(y_test_2,y_pred8))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92     64099
           1       0.57      0.21      0.31     12005

    accuracy                           0.85     76104
   macro avg       0.72      0.59      0.61     76104
weighted avg       0.82      0.85      0.82     76104

[[62234  1865]
 [ 9491  2514]]
0.850783138862609


In [ ]:
data = {'0.70-0.30': [0.8509, 0.8445,0.8506 ],'0.60-0.40': [0.8524,0.8445 , 0.8506],'0.75-0.25': [0.8527,0.8445 ,0.8506]}
data = pd.DataFrame(data)
print(data)

   0.70-0.30  0.60-0.40  0.75-0.25
0     0.8509     0.8524     0.8527
1     0.8445     0.8445     0.8445
2     0.8506     0.8506     0.8506


SVM

In [ ]:
sample_data= data.sample(n=2000, replace=True, random_state=42)

In [ ]:
X=sample_data.drop(['Diabetes_012'],axis=1)
y = sample_data['Diabetes_012']

In [ ]:
X

HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
121958       1         0          1   35       0       0   
146867       0         0          0   23       0       0   
131932       0         1          1   25       0       0   
103694       1         1          1   29       1       0   
119879       1         0          1   45       1       0   
...        ...       ...        ...  ...     ...     ...   
74910        0         0          1   31       0       0   
52375        1         0          1   31       0       0   
121826       1         1          1   41       1       0   
35435        0         0          1   27       0       0   
96443        0         0          1   24       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
121958                     0             0       1        1  ...   
146867                     0             0       1        1  ...   
131932                     0             1       1        1  ...   
103694                     0             1       0        1  ...   
119879                     0             1       1        0  ...   
...                      ...           ...     ...      ...  ...   
74910                      0             1       1        1  ...   
52375                      0             0       1        1  ...   
121826                     0             0       1        1  ...   
35435                      0             1       1        1  ...   
96443                      0             1       1        1  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
121958              1            0        3        15         0         1   
146867              1            1        2         0         0         0   
131932              1            0        2         0         3         0   
103694              1            0        3         0         0         0   
119879              1            1        1        15         0         0   
...               ...          ...      ...       ...       ...       ...   
74910               1            0        3         0         1         0   
52375               1            0        3         3         3         0   
121826              1            0        4         0         0         0   
35435               1            0        2        10         0         0   
96443               1            0        1         0         0         0   

        Sex  Age  Education  Income  
121958    0   11          5       6  
146867    0    5          6       6  
131932    0    9          6       8  
103694    1   11          6       7  
119879    0    5          4       1  
...     ...  ...        ...     ...  
74910     1    4          6       8  
52375     1    2          4       1  
121826    0   11          3       1  
35435     0    7          6       6  
96443     1    2          6       6  

[2000 rows x 21 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, train_size=0.70, random_state=42)

In [ ]:
svm =SVC(kernel='linear')
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
svm_results = pd.DataFrame({'predicted': y_pred, 'Actual': y_test})
print(svm_results.head(10))
print(classification_report(y_test, y_pred))
z = confusion_matrix(y_test, y_pred)
print(z)
print(accuracy_score(y_test, y_pred))

        predicted  Actual
11555           0       0
21918           0       0
46514           0       0
230590          0       0
116148          0       0
212521          0       0
183808          0       0
12175           0       1
239629          0       1
112221          0       0
              precision    recall  f1-score   support

           0       0.84      1.00      0.92       507
           1       0.00      0.00      0.00        93

    accuracy                           0.84       600
   macro avg       0.42      0.50      0.46       600
weighted avg       0.71      0.84      0.77       600

[[507   0]
 [ 93   0]]
0.845


In [ ]:
svm =SVC(kernel='sigmoid')
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
y_pred
svm_results = pd.DataFrame({'predicted': y_pred, 'Actual': y_test})
print(svm_results.head(10))
print(classification_report(y_test, y_pred))
z = confusion_matrix(y_test, y_pred)
print(z)
print(accuracy_score(y_test, y_pred))

        predicted  Actual
11555           0       0
21918           0       0
46514           0       0
230590          0       0
116148          0       0
212521          0       0
183808          0       0
12175           0       1
239629          0       1
112221          0       0
              precision    recall  f1-score   support

           0       0.84      0.98      0.91       507
           1       0.14      0.02      0.04        93

    accuracy                           0.83       600
   macro avg       0.49      0.50      0.47       600
weighted avg       0.74      0.83      0.77       600

[[495  12]
 [ 91   2]]
0.8283333333333334


svm for original data

In [ ]:
svm =SVC(kernel='poly')
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
y_pred
svm_results = pd.DataFrame({'predicted': y_pred, 'Actual': y_test})
print(svm_results.head(10))
print(classification_report(y_test, y_pred))
z = confusion_matrix(y_test, y_pred)
print(z)
print(accuracy_score(y_test, y_pred))

        predicted  Actual
11555           0       0
21918           0       0
46514           0       0
230590          0       0
116148          0       0
212521          0       0
183808          0       0
12175           0       1
239629          0       1
112221          0       0
              precision    recall  f1-score   support

           0       0.85      1.00      0.92       507
           1       0.67      0.02      0.04        93

    accuracy                           0.85       600
   macro avg       0.76      0.51      0.48       600
weighted avg       0.82      0.85      0.78       600

[[506   1]
 [ 91   2]]
0.8466666666666667


svm for after removing multi-collinearity

In [ ]:
X_1=X.drop(['Education','CholCheck','AnyHealthcare','BMI','Age','GenHlth','Income','Veggies'],axis=1)
y_1=y
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X_1, y_1, test_size=0.30, train_size=0.70, random_state=42)
svm =SVC(kernel='poly')
svm.fit(X_train_1,y_train_1)
y_pred1=svm.predict(X_test_1)
y_pred1
svm_results = pd.DataFrame({'predicted': y_pred1, 'Actual': y_test_1})
print(svm_results.head(10))
print(classification_report(y_test, y_pred1))
z = confusion_matrix(y_test, y_pred1)
print(z)
print(accuracy_score(y_test, y_pred1))

        predicted  Actual
11555           0       0
21918           0       0
46514           0       0
230590          0       0
116148          0       0
212521          0       0
183808          0       0
12175           1       1
239629          0       1
112221          0       0
              precision    recall  f1-score   support

           0       0.86      0.98      0.92       507
           1       0.56      0.11      0.18        93

    accuracy                           0.85       600
   macro avg       0.71      0.55      0.55       600
weighted avg       0.81      0.85      0.80       600

[[499   8]
 [ 83  10]]
0.8483333333333334


svm for after removing insignificant variable

In [ ]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_2, y_2, test_size=0.30, train_size=0.70, random_state=42)
svm =SVC(kernel='poly')
svm.fit(X_train_2,y_train_2)
y_pred2=svm.predict(X_test_2)
y_pred2
svm_results = pd.DataFrame({'predicted': y_pred2, 'Actual': y_test_2})
print(svm_results.head(10))
print(classification_report(y_test_2, y_pred2))
z = confusion_matrix(y_test_2, y_pred2)
print(z)
print(accuracy_score(y_test_2, y_pred2))

        predicted  Actual
219620          0       0
132821          0       0
151862          0       0
139717          0       0
239235          0       0
68060           0       1
34035           0       1
159729          0       0
144332          0       0
228468          0       0
              precision    recall  f1-score   support

           0       0.85      1.00      0.92     64180
           1       0.64      0.02      0.03     11924

    accuracy                           0.84     76104
   macro avg       0.74      0.51      0.47     76104
weighted avg       0.81      0.84      0.78     76104

[[64078   102]
 [11742   182]]
0.8443708609271523


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, train_size=0.60, random_state=42)
svm =SVC(kernel='poly')
svm.fit(X_train,y_train)
y_pred3=svm.predict(X_test)
y_pred3
svm_results = pd.DataFrame({'predicted': y_pred3, 'Actual': y_test})
print(svm_results.head(10))
print(classification_report(y_test, y_pred3))
z = confusion_matrix(y_test, y_pred3)
print(z)
print(accuracy_score(y_test, y_pred3))

        predicted  Actual
160045          0       0
123549          0       1
211428          0       1
108435          0       0
169511          0       0
91477           0       1
101489          0       0
135022          0       0
69615           0       0
20001           0       0
              precision    recall  f1-score   support

           0       0.84      1.00      0.91     16833
           1       0.64      0.00      0.01      3167

    accuracy                           0.84     20000
   macro avg       0.74      0.50      0.46     20000
weighted avg       0.81      0.84      0.77     20000

[[16825     8]
 [ 3153    14]]
0.84195


In [ ]:
svm =SVC(kernel='poly')
svm.fit(X_train_1,y_train_1)
y_pred4=svm.predict(X_test_1)
y_pred4
svm_results = pd.DataFrame({'predicted': y_pred4, 'Actual': y_test_1})
print(svm_results.head(10))
print(classification_report(y_test_1, y_pred4))
z = confusion_matrix(y_test_1, y_pred4)
print(z)
print(accuracy_score(y_test_1, y_pred4))

        predicted  Actual
160045          0       0
123549          0       1
211428          0       1
108435          0       0
169511          0       0
91477           0       1
101489          0       0
135022          0       0
69615           0       0
20001           0       0
              precision    recall  f1-score   support

           0       0.84      1.00      0.91     12644
           1       0.00      0.00      0.00      2356

    accuracy                           0.84     15000
   macro avg       0.42      0.50      0.46     15000
weighted avg       0.71      0.84      0.77     15000

[[12644     0]
 [ 2356     0]]
0.8429333333333333


In [ ]:
svm =SVC(kernel='poly')
svm.fit(X_train_2,y_train_2)
y_pred5=svm.predict(X_test_2)
y_pred5
svm_results = pd.DataFrame({'predicted': y_pred5, 'Actual': y_test_2})
print(svm_results.head(10))
print(classification_report(y_test_2, y_pred5))
z = confusion_matrix(y_test_2, y_pred5)
print(z)
print(accuracy_score(y_test_2, y_pred5))

        predicted  Actual
44697           0       0
1443            0       0
77119           0       1
185502          0       0
13210           0       0
114630          0       0
81769           0       1
27026           0       0
221114          0       1
165606          0       0
              precision    recall  f1-score   support

           0       0.84      1.00      0.91     64144
           1       0.56      0.00      0.00     11960

    accuracy                           0.84     76104
   macro avg       0.70      0.50      0.46     76104
weighted avg       0.80      0.84      0.77     76104

[[64140     4]
 [11955     5]]
0.8428597708399033


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, train_size=0.75, random_state=42)
svm =SVC(kernel='poly')
svm.fit(X_train,y_train)
y_pred6=svm.predict(X_test)
y_pred6
svm_results = pd.DataFrame({'predicted': y_pred6, 'Actual': y_test})
print(svm_results.head(10))
print(classification_report(y_test, y_pred6))
z = confusion_matrix(y_test, y_pred6)
print(z)
print(accuracy_score(y_test, y_pred6))

        predicted  Actual
160045          0       0
123549          0       1
211428          0       1
108435          0       0
169511          0       0
91477           0       1
101489          0       0
135022          0       0
69615           0       0
20001           0       0
              precision    recall  f1-score   support

           0       0.84      1.00      0.92     10542
           1       1.00      0.00      0.00      1958

    accuracy                           0.84     12500
   macro avg       0.92      0.50      0.46     12500
weighted avg       0.87      0.84      0.77     12500

[[10542     0]
 [ 1955     3]]
0.8436


In [ ]:
svm =SVC(kernel='poly')
svm.fit(X_train_1,y_train_1)
y_pred7=svm.predict(X_test_1)
y_pred7
svm_results = pd.DataFrame({'predicted': y_pred7, 'Actual': y_test_1})
print(svm_results.head(10))
print(classification_report(y_test, y_pred7))
z = confusion_matrix(y_test, y_pred7)
print(z)
print(accuracy_score(y_test, y_pred7))

In [ ]:
svm =SVC(kernel='poly')
svm.fit(X_train_2,y_train_2)
y_pred8=svm.predict(X_test_2)
y_pred8
svm_results = pd.DataFrame({'predicted': y_pred8, 'Actual': y_test_2})
print(svm_results.head(10))
print(classification_report(y_test_2, y_pred8))
z = confusion_matrix(y_test_2, y_pred8)
print(z)
print(accuracy_score(y_test_2, y_pred8))

In [ ]:
data = {'0.70-0.30': [0.8432, 0.8445,0.8506 ],'0.60-0.40': [0.8524,0.8445 , 0.8506],'0.75-0.25': [0.8527,0.8445 ,0.8506]}
data = pd.DataFrame(data)
print(data)

In [ ]:
corr=X.corr()
htmp=sns.heatmap(X.corr(),annot=True)
htmp